# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e758979fd12dfbc5e347d1f63a812014e4d46752d0280756ec85518f78c0bd5d8b32319dc3a831a742dc8ece7e90aa45282260f147099dd0669cbb14108c0448

test:
  secret_key_base: d6195a88c7a6133c54f23f36c6140d22643ea6bd915333a163c9871c51bb7c6cd5ea04c13a78133136ffd9a879db04d05b8378b185ccc4eaa4eff0e7cb2cc0c3

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
